set -g base-index 1
setw -g mouse on

# Show only window numbers
set -g window-status-format " #I "
set -g window-status-current-format "#[bg=blue,fg=#ffffff,bold] #I #[default]"
set -g window-status-separator " "
set -g status-style "bg=default"
set -g status-left "  "
set -g message-style "bg=default"
set -g status-justify left
set -g status-right "#[bg=green,fg=#ffffff,bold] #S #[default]  "
